server:
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/work?characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 520JIAYOUlc
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lc.work.model